/****************************************************************************
* Copyright (C) 2019 Eric Mor
*
* This file is part of Spore ModCreatorKit.
*
* Spore ModAPI is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
****************************************************************************/
#pragma once

#include <Spore\Detouring.h>
#include <Spore\Swarm\cSwarmManager.h>

/* Class generated by the ModAPI. You must NOT:
/*    - Create new instances of this class.
/*    - Make another class inherit this class.
/*    - Add new members to this class. You can add methods, however.
/* --------------------------------------------------------------- */
class DetouredSwarmManager : public Swarm::cSwarmManager
{
public:

	// Call this static method in the DllMain function to apply the function detourings of this class.
	static long AttachDetour();

	// int GetDirectoryAndEffectIndex(uint32_t instanceID, uint32_t groupID)
#pragma DisableOptimization
	static int __fastcall DetouredGetDirectoryAndEffectIndex_redirected( DetouredSwarmManager* _This, int, uint32_t instanceID, uint32_t groupID)
	{
		return (( DetouredSwarmManager*)_This)->DetouredGetDirectoryAndEffectIndex(instanceID, groupID);
	}
	typedef int (__thiscall* GetDirectoryAndEffectIndex_original_t)( DetouredSwarmManager*, uint32_t instanceID, uint32_t groupID);
	static GetDirectoryAndEffectIndex_original_t GetDirectoryAndEffectIndex_original;
	int DetouredGetDirectoryAndEffectIndex(uint32_t instanceID, uint32_t groupID) ;


};
